-- Total orders and revenue generated by each sellers
SELECT
    oi.seller_id,
    COUNT(DISTINCT oi.order_id) AS total_orders,
    ROUND(SUM(oi.price), 2) AS seller_revenue
FROM order_items oi
JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.order_status = 'delivered'
GROUP BY oi.seller_id
ORDER BY seller_revenue DESC;


-- Seller revenue tied to non-delivered orders
SELECT
    oi.seller_id,
    ROUND(SUM(oi.price), 2) AS revenue_at_risk
FROM order_items oi
JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.order_status <> 'delivered'
GROUP BY oi.seller_id
ORDER BY revenue_at_risk DESC;


-- Seller quality and Revenue trade-off
SELECT
    oi.seller_id,
    ROUND(SUM(oi.price), 2) AS seller_revenue,
    ROUND(AVG(r.review_score), 2) AS avg_review_score,
    COUNT(r.review_score) AS review_count
FROM order_items oi
JOIN orders o
    ON oi.order_id = o.order_id
JOIN order_reviews r
    ON o.order_id = r.order_id
GROUP BY oi.seller_id
HAVING COUNT(r.review_score) > 50
ORDER BY seller_revenue DESC;


-- Delay rate of Sellers
SELECT
    oi.seller_id,
    COUNT(DISTINCT o.order_id) AS delivered_orders,
    COUNT(DISTINCT o.order_id) FILTER (
        WHERE o.order_delivered_customer_date > o.order_estimated_delivery_date
    ) AS delayed_orders,
    ROUND(
        COUNT(DISTINCT o.order_id) FILTER (
            WHERE o.order_delivered_customer_date > o.order_estimated_delivery_date
        )::NUMERIC
        / COUNT(DISTINCT o.order_id),
        4
    )*100 AS delay_rate
FROM order_items oi
JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.order_status = 'delivered'
GROUP BY oi.seller_id
HAVING COUNT(DISTINCT o.order_id) > 50
ORDER BY delay_rate DESC;


-- Seller risk score based on delayed and non-delivered orders
WITH seller_orders AS (
    SELECT
        oi.seller_id,
        COUNT(DISTINCT o.order_id) AS total_orders,
        COUNT(DISTINCT o.order_id) FILTER (
            WHERE o.order_status <> 'delivered'
               OR o.order_delivered_customer_date > o.order_estimated_delivery_date
        ) AS problematic_orders
    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id
    GROUP BY oi.seller_id
)
SELECT
    seller_id,
    total_orders,
    problematic_orders,
    ROUND(problematic_orders::NUMERIC / total_orders, 4)*100 AS risk_score
FROM seller_orders
WHERE total_orders > 50
ORDER BY risk_score DESC;